"""added min,max,job_code  to Jobs model

Revision ID: da12fcee97a7
Revises: 
Create Date: 2026-02-14 16:28:53.153244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da12fcee97a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_code', sa.String(), nullable=False))
    op.add_column('jobs', sa.Column('Min_sal', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('Max_sal', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'jobs', ['job_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_column('jobs', 'Max_sal')
    op.drop_column('jobs', 'Min_sal')
    op.drop_column('jobs', 'job_code')
    # ### end Alembic commands ###
